// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_TVN8t6QD0gJSGxJ7erJNykKj8bEqJJE',
    appId: '1:1041947623736:web:ca1ea724fdfefbfad801cd',
    messagingSenderId: '1041947623736',
    projectId: 'fullproject-50119',
    authDomain: 'fullproject-50119.firebaseapp.com',
    storageBucket: 'fullproject-50119.appspot.com',
    measurementId: 'G-LPLL82SD11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXuvwCoXwXMQeuCLTIVK_QFoDnZlODfGA',
    appId: '1:1041947623736:android:ff537fc10a94e558d801cd',
    messagingSenderId: '1041947623736',
    projectId: 'fullproject-50119',
    storageBucket: 'fullproject-50119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDftALTLwQzx6GKzTLSB_4ACzf4oI0rz3o',
    appId: '1:1041947623736:ios:b3c1b4ae48cee5aed801cd',
    messagingSenderId: '1041947623736',
    projectId: 'fullproject-50119',
    storageBucket: 'fullproject-50119.appspot.com',
    iosClientId: '1041947623736-bk0ejf20i05cd3feqiav0smqr43055j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDftALTLwQzx6GKzTLSB_4ACzf4oI0rz3o',
    appId: '1:1041947623736:ios:b3c1b4ae48cee5aed801cd',
    messagingSenderId: '1041947623736',
    projectId: 'fullproject-50119',
    storageBucket: 'fullproject-50119.appspot.com',
    iosClientId: '1041947623736-bk0ejf20i05cd3feqiav0smqr43055j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullFirebase',
  );
}
